/* Generated by Babel */
'use strict';

(function () {

  var $ = document.querySelector.bind(document);
  var $$ = document.querySelectorAll.bind(document);
  var canvas = document.createElement('canvas');
  var ctx = canvas.getContext('2d');

  var onImageLoad = function onImageLoad(image) {
    console.log('Picture Load: Done');
    ctx.drawImage(image, 192, 192);
  };

  var setup = function setup() {
    var body = $('body');
    alert(body);

    canvas.setAttribute('width', 500);
    canvas.setAttribute('height', 700);

    console.log(canvas.width);

    var image = new Image();

    image.src = "img/robot-cute-character-waving-hand.jpg";

    image.onload = onImageLoad(image);
  };

  setup();
})();